-- WCAG 2.2 Criteria Seed Data
-- All 86 success criteria with Swedish translations

INSERT INTO wcag_criteria (id, principle, guideline, level, name_en, name_sv, description_en, description_sv, understanding_url, techniques_url) VALUES

-- ============================================
-- PRINCIPLE 1: PERCEIVABLE
-- ============================================

-- Guideline 1.1: Text Alternatives
('1.1.1', 1, '1.1', 'A', 'Non-text Content', 'Innehåll som inte är text', 'All non-text content that is presented to the user has a text alternative that serves the equivalent purpose.', 'Allt innehåll som inte är text och som presenteras för användaren har ett textalternativ som tjänar motsvarande syfte.', 'https://www.w3.org/WAI/WCAG22/Understanding/non-text-content', 'https://www.w3.org/WAI/WCAG22/Techniques/#non-text-content'),

-- Guideline 1.2: Time-based Media
('1.2.1', 1, '1.2', 'A', 'Audio-only and Video-only (Prerecorded)', 'Endast ljud och endast video (förinspelat)', 'For prerecorded audio-only and prerecorded video-only media, alternatives are provided.', 'För förinspelat endast ljud och förinspelat endast video tillhandahålls alternativ.', 'https://www.w3.org/WAI/WCAG22/Understanding/audio-only-and-video-only-prerecorded', 'https://www.w3.org/WAI/WCAG22/Techniques/#audio-only-and-video-only-prerecorded'),
('1.2.2', 1, '1.2', 'A', 'Captions (Prerecorded)', 'Textning (förinspelat)', 'Captions are provided for all prerecorded audio content in synchronized media.', 'Textning tillhandahålls för allt förinspelat ljudinnehåll i synkroniserade medier.', 'https://www.w3.org/WAI/WCAG22/Understanding/captions-prerecorded', 'https://www.w3.org/WAI/WCAG22/Techniques/#captions-prerecorded'),
('1.2.3', 1, '1.2', 'A', 'Audio Description or Media Alternative (Prerecorded)', 'Syntolkning eller mediealternativ (förinspelat)', 'An alternative for time-based media or audio description is provided for prerecorded video content.', 'Ett alternativ för tidsbaserade medier eller syntolkning tillhandahålls för förinspelat videoinnehåll.', 'https://www.w3.org/WAI/WCAG22/Understanding/audio-description-or-media-alternative-prerecorded', 'https://www.w3.org/WAI/WCAG22/Techniques/#audio-description-or-media-alternative-prerecorded'),
('1.2.4', 1, '1.2', 'AA', 'Captions (Live)', 'Textning (live)', 'Captions are provided for all live audio content in synchronized media.', 'Textning tillhandahålls för allt livebaserat ljudinnehåll i synkroniserade medier.', 'https://www.w3.org/WAI/WCAG22/Understanding/captions-live', 'https://www.w3.org/WAI/WCAG22/Techniques/#captions-live'),
('1.2.5', 1, '1.2', 'AA', 'Audio Description (Prerecorded)', 'Syntolkning (förinspelat)', 'Audio description is provided for all prerecorded video content in synchronized media.', 'Syntolkning tillhandahålls för allt förinspelat videoinnehåll i synkroniserade medier.', 'https://www.w3.org/WAI/WCAG22/Understanding/audio-description-prerecorded', 'https://www.w3.org/WAI/WCAG22/Techniques/#audio-description-prerecorded'),
('1.2.6', 1, '1.2', 'AAA', 'Sign Language (Prerecorded)', 'Teckenspråk (förinspelat)', 'Sign language interpretation is provided for all prerecorded audio content.', 'Teckenspråkstolkning tillhandahålls för allt förinspelat ljudinnehåll.', 'https://www.w3.org/WAI/WCAG22/Understanding/sign-language-prerecorded', 'https://www.w3.org/WAI/WCAG22/Techniques/#sign-language-prerecorded'),
('1.2.7', 1, '1.2', 'AAA', 'Extended Audio Description (Prerecorded)', 'Utökad syntolkning (förinspelat)', 'Extended audio description is provided for all prerecorded video content.', 'Utökad syntolkning tillhandahålls för allt förinspelat videoinnehåll.', 'https://www.w3.org/WAI/WCAG22/Understanding/extended-audio-description-prerecorded', 'https://www.w3.org/WAI/WCAG22/Techniques/#extended-audio-description-prerecorded'),
('1.2.8', 1, '1.2', 'AAA', 'Media Alternative (Prerecorded)', 'Mediealternativ (förinspelat)', 'An alternative for time-based media is provided for all prerecorded synchronized media.', 'Ett alternativ för tidsbaserade medier tillhandahålls för alla förinspelade synkroniserade medier.', 'https://www.w3.org/WAI/WCAG22/Understanding/media-alternative-prerecorded', 'https://www.w3.org/WAI/WCAG22/Techniques/#media-alternative-prerecorded'),
('1.2.9', 1, '1.2', 'AAA', 'Audio-only (Live)', 'Endast ljud (live)', 'An alternative for time-based media is provided for all live audio-only content.', 'Ett alternativ för tidsbaserade medier tillhandahålls för allt liveinnehåll med endast ljud.', 'https://www.w3.org/WAI/WCAG22/Understanding/audio-only-live', 'https://www.w3.org/WAI/WCAG22/Techniques/#audio-only-live'),

-- Guideline 1.3: Adaptable
('1.3.1', 1, '1.3', 'A', 'Info and Relationships', 'Information och relationer', 'Information, structure, and relationships conveyed through presentation can be programmatically determined.', 'Information, struktur och relationer som förmedlas genom presentation kan bestämmas programmatiskt.', 'https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships', 'https://www.w3.org/WAI/WCAG22/Techniques/#info-and-relationships'),
('1.3.2', 1, '1.3', 'A', 'Meaningful Sequence', 'Meningsfull ordning', 'When the sequence in which content is presented affects its meaning, a correct reading sequence can be programmatically determined.', 'När ordningen i vilken innehåll presenteras påverkar dess betydelse, kan en korrekt läsordning bestämmas programmatiskt.', 'https://www.w3.org/WAI/WCAG22/Understanding/meaningful-sequence', 'https://www.w3.org/WAI/WCAG22/Techniques/#meaningful-sequence'),
('1.3.3', 1, '1.3', 'A', 'Sensory Characteristics', 'Sensoriska kännetecken', 'Instructions do not rely solely on sensory characteristics of components.', 'Instruktioner förlitar sig inte enbart på sensoriska kännetecken hos komponenter.', 'https://www.w3.org/WAI/WCAG22/Understanding/sensory-characteristics', 'https://www.w3.org/WAI/WCAG22/Techniques/#sensory-characteristics'),
('1.3.4', 1, '1.3', 'AA', 'Orientation', 'Orientering', 'Content does not restrict its view and operation to a single display orientation.', 'Innehåll begränsar inte sin visning och användning till en enda visningsorientering.', 'https://www.w3.org/WAI/WCAG22/Understanding/orientation', 'https://www.w3.org/WAI/WCAG22/Techniques/#orientation'),
('1.3.5', 1, '1.3', 'AA', 'Identify Input Purpose', 'Identifiera inmatningssyfte', 'The purpose of each input field collecting user information can be programmatically determined.', 'Syftet med varje inmatningsfält som samlar in användarinformation kan bestämmas programmatiskt.', 'https://www.w3.org/WAI/WCAG22/Understanding/identify-input-purpose', 'https://www.w3.org/WAI/WCAG22/Techniques/#identify-input-purpose'),
('1.3.6', 1, '1.3', 'AAA', 'Identify Purpose', 'Identifiera syfte', 'The purpose of User Interface components, icons, and regions can be programmatically determined.', 'Syftet med användargränssnittskomponenter, ikoner och regioner kan bestämmas programmatiskt.', 'https://www.w3.org/WAI/WCAG22/Understanding/identify-purpose', 'https://www.w3.org/WAI/WCAG22/Techniques/#identify-purpose'),

-- Guideline 1.4: Distinguishable
('1.4.1', 1, '1.4', 'A', 'Use of Color', 'Användning av färg', 'Color is not used as the only visual means of conveying information.', 'Färg används inte som det enda visuella sättet att förmedla information.', 'https://www.w3.org/WAI/WCAG22/Understanding/use-of-color', 'https://www.w3.org/WAI/WCAG22/Techniques/#use-of-color'),
('1.4.2', 1, '1.4', 'A', 'Audio Control', 'Ljudkontroll', 'If audio plays automatically for more than 3 seconds, a mechanism is available to pause, stop, or control volume.', 'Om ljud spelas automatiskt i mer än 3 sekunder, finns en mekanism för att pausa, stoppa eller kontrollera volymen.', 'https://www.w3.org/WAI/WCAG22/Understanding/audio-control', 'https://www.w3.org/WAI/WCAG22/Techniques/#audio-control'),
('1.4.3', 1, '1.4', 'AA', 'Contrast (Minimum)', 'Kontrast (minimum)', 'Text and images of text have a contrast ratio of at least 4.5:1.', 'Text och bilder av text har ett kontrastförhållande på minst 4,5:1.', 'https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum', 'https://www.w3.org/WAI/WCAG22/Techniques/#contrast-minimum'),
('1.4.4', 1, '1.4', 'AA', 'Resize Text', 'Ändra textstorlek', 'Text can be resized without assistive technology up to 200 percent without loss of content or functionality.', 'Text kan ändras i storlek utan hjälpmedel upp till 200 procent utan förlust av innehåll eller funktionalitet.', 'https://www.w3.org/WAI/WCAG22/Understanding/resize-text', 'https://www.w3.org/WAI/WCAG22/Techniques/#resize-text'),
('1.4.5', 1, '1.4', 'AA', 'Images of Text', 'Bilder av text', 'If the technologies being used can achieve the visual presentation, text is used to convey information rather than images of text.', 'Om teknikerna som används kan uppnå den visuella presentationen, används text för att förmedla information snarare än bilder av text.', 'https://www.w3.org/WAI/WCAG22/Understanding/images-of-text', 'https://www.w3.org/WAI/WCAG22/Techniques/#images-of-text'),
('1.4.6', 1, '1.4', 'AAA', 'Contrast (Enhanced)', 'Kontrast (förbättrad)', 'Text and images of text have a contrast ratio of at least 7:1.', 'Text och bilder av text har ett kontrastförhållande på minst 7:1.', 'https://www.w3.org/WAI/WCAG22/Understanding/contrast-enhanced', 'https://www.w3.org/WAI/WCAG22/Techniques/#contrast-enhanced'),
('1.4.7', 1, '1.4', 'AAA', 'Low or No Background Audio', 'Lågt eller inget bakgrundsljud', 'For prerecorded audio-only content, background sounds are at least 20 dB lower than foreground speech.', 'För förinspelat innehåll med endast ljud är bakgrundsljud minst 20 dB lägre än talat i förgrunden.', 'https://www.w3.org/WAI/WCAG22/Understanding/low-or-no-background-audio', 'https://www.w3.org/WAI/WCAG22/Techniques/#low-or-no-background-audio'),
('1.4.8', 1, '1.4', 'AAA', 'Visual Presentation', 'Visuell presentation', 'For blocks of text, a mechanism is available to customize visual presentation.', 'För textblock finns en mekanism tillgänglig för att anpassa visuell presentation.', 'https://www.w3.org/WAI/WCAG22/Understanding/visual-presentation', 'https://www.w3.org/WAI/WCAG22/Techniques/#visual-presentation'),
('1.4.9', 1, '1.4', 'AAA', 'Images of Text (No Exception)', 'Bilder av text (inga undantag)', 'Images of text are only used for pure decoration or where a particular presentation is essential.', 'Bilder av text används endast för ren dekoration eller där en viss presentation är väsentlig.', 'https://www.w3.org/WAI/WCAG22/Understanding/images-of-text-no-exception', 'https://www.w3.org/WAI/WCAG22/Techniques/#images-of-text-no-exception'),
('1.4.10', 1, '1.4', 'AA', 'Reflow', 'Omflöde', 'Content can be presented without loss of information or functionality, and without scrolling in two dimensions.', 'Innehåll kan presenteras utan förlust av information eller funktionalitet, och utan scrollning i två dimensioner.', 'https://www.w3.org/WAI/WCAG22/Understanding/reflow', 'https://www.w3.org/WAI/WCAG22/Techniques/#reflow'),
('1.4.11', 1, '1.4', 'AA', 'Non-text Contrast', 'Kontrast för icke-text', 'Visual information required to identify UI components and graphical objects has a contrast ratio of at least 3:1.', 'Visuell information som krävs för att identifiera UI-komponenter och grafiska objekt har ett kontrastförhållande på minst 3:1.', 'https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast', 'https://www.w3.org/WAI/WCAG22/Techniques/#non-text-contrast'),
('1.4.12', 1, '1.4', 'AA', 'Text Spacing', 'Textavstånd', 'No loss of content or functionality occurs when adjusting line height, paragraph spacing, letter spacing, and word spacing.', 'Ingen förlust av innehåll eller funktionalitet uppstår vid justering av radavstånd, styckeavstånd, teckenavstånd och ordavstånd.', 'https://www.w3.org/WAI/WCAG22/Understanding/text-spacing', 'https://www.w3.org/WAI/WCAG22/Techniques/#text-spacing'),
('1.4.13', 1, '1.4', 'AA', 'Content on Hover or Focus', 'Innehåll vid hovring eller fokus', 'Additional content that appears on hover or focus can be dismissed, hovered over, and is persistent.', 'Ytterligare innehåll som visas vid hovring eller fokus kan avfärdas, hovras över och är beständigt.', 'https://www.w3.org/WAI/WCAG22/Understanding/content-on-hover-or-focus', 'https://www.w3.org/WAI/WCAG22/Techniques/#content-on-hover-or-focus'),

-- ============================================
-- PRINCIPLE 2: OPERABLE
-- ============================================

-- Guideline 2.1: Keyboard Accessible
('2.1.1', 2, '2.1', 'A', 'Keyboard', 'Tangentbord', 'All functionality of the content is operable through a keyboard interface.', 'All funktionalitet i innehållet kan användas via ett tangentbordsgränssnitt.', 'https://www.w3.org/WAI/WCAG22/Understanding/keyboard', 'https://www.w3.org/WAI/WCAG22/Techniques/#keyboard'),
('2.1.2', 2, '2.1', 'A', 'No Keyboard Trap', 'Ingen tangentbordsfälla', 'If keyboard focus can be moved to a component, focus can be moved away using only a keyboard.', 'Om tangentbordsfokus kan flyttas till en komponent, kan fokus flyttas bort med endast ett tangentbord.', 'https://www.w3.org/WAI/WCAG22/Understanding/no-keyboard-trap', 'https://www.w3.org/WAI/WCAG22/Techniques/#no-keyboard-trap'),
('2.1.3', 2, '2.1', 'AAA', 'Keyboard (No Exception)', 'Tangentbord (inga undantag)', 'All functionality of the content is operable through a keyboard interface without requiring specific timings.', 'All funktionalitet i innehållet kan användas via ett tangentbordsgränssnitt utan att kräva specifika tidpunkter.', 'https://www.w3.org/WAI/WCAG22/Understanding/keyboard-no-exception', 'https://www.w3.org/WAI/WCAG22/Techniques/#keyboard-no-exception'),
('2.1.4', 2, '2.1', 'A', 'Character Key Shortcuts', 'Kortkommandon med tecken', 'If a keyboard shortcut uses only letter, punctuation, number, or symbol characters, it can be turned off or remapped.', 'Om ett kortkommando endast använder bokstäver, skiljetecken, siffror eller symboler, kan det stängas av eller ändras.', 'https://www.w3.org/WAI/WCAG22/Understanding/character-key-shortcuts', 'https://www.w3.org/WAI/WCAG22/Techniques/#character-key-shortcuts'),

-- Guideline 2.2: Enough Time
('2.2.1', 2, '2.2', 'A', 'Timing Adjustable', 'Justerbar tidsgräns', 'For time limits, users can turn off, adjust, or extend the time limit.', 'För tidsgränser kan användare stänga av, justera eller förlänga tidsgränsen.', 'https://www.w3.org/WAI/WCAG22/Understanding/timing-adjustable', 'https://www.w3.org/WAI/WCAG22/Techniques/#timing-adjustable'),
('2.2.2', 2, '2.2', 'A', 'Pause, Stop, Hide', 'Pausa, stoppa, dölj', 'For moving, blinking, scrolling, or auto-updating information, a mechanism is available to pause, stop, or hide it.', 'För rörlig, blinkande, rullande eller automatiskt uppdaterad information finns en mekanism för att pausa, stoppa eller dölja den.', 'https://www.w3.org/WAI/WCAG22/Understanding/pause-stop-hide', 'https://www.w3.org/WAI/WCAG22/Techniques/#pause-stop-hide'),
('2.2.3', 2, '2.2', 'AAA', 'No Timing', 'Ingen tidsbegränsning', 'Timing is not an essential part of the event or activity, except for non-interactive synchronized media and real-time events.', 'Timing är inte en väsentlig del av händelsen eller aktiviteten, förutom icke-interaktiva synkroniserade medier och realtidshändelser.', 'https://www.w3.org/WAI/WCAG22/Understanding/no-timing', 'https://www.w3.org/WAI/WCAG22/Techniques/#no-timing'),
('2.2.4', 2, '2.2', 'AAA', 'Interruptions', 'Avbrott', 'Interruptions can be postponed or suppressed by the user, except for emergencies.', 'Avbrott kan skjutas upp eller undertryckas av användaren, förutom vid nödsituationer.', 'https://www.w3.org/WAI/WCAG22/Understanding/interruptions', 'https://www.w3.org/WAI/WCAG22/Techniques/#interruptions'),
('2.2.5', 2, '2.2', 'AAA', 'Re-authenticating', 'Återautentisering', 'When an authenticated session expires, the user can continue the activity without loss of data after re-authenticating.', 'När en autentiserad session upphör kan användaren fortsätta aktiviteten utan dataförlust efter återautentisering.', 'https://www.w3.org/WAI/WCAG22/Understanding/re-authenticating', 'https://www.w3.org/WAI/WCAG22/Techniques/#re-authenticating'),
('2.2.6', 2, '2.2', 'AAA', 'Timeouts', 'Tidsgränser', 'Users are warned of the duration of any user inactivity that could cause data loss.', 'Användare varnas för längden på eventuell användariinaktivitet som kan orsaka dataförlust.', 'https://www.w3.org/WAI/WCAG22/Understanding/timeouts', 'https://www.w3.org/WAI/WCAG22/Techniques/#timeouts'),

-- Guideline 2.3: Seizures and Physical Reactions
('2.3.1', 2, '2.3', 'A', 'Three Flashes or Below Threshold', 'Tre blinkningar eller under tröskelvärde', 'Pages do not contain anything that flashes more than three times per second.', 'Sidor innehåller inte något som blinkar mer än tre gånger per sekund.', 'https://www.w3.org/WAI/WCAG22/Understanding/three-flashes-or-below-threshold', 'https://www.w3.org/WAI/WCAG22/Techniques/#three-flashes-or-below-threshold'),
('2.3.2', 2, '2.3', 'AAA', 'Three Flashes', 'Tre blinkningar', 'Pages do not contain anything that flashes more than three times per second.', 'Sidor innehåller inte något som blinkar mer än tre gånger per sekund.', 'https://www.w3.org/WAI/WCAG22/Understanding/three-flashes', 'https://www.w3.org/WAI/WCAG22/Techniques/#three-flashes'),
('2.3.3', 2, '2.3', 'AAA', 'Animation from Interactions', 'Animation från interaktioner', 'Motion animation triggered by interaction can be disabled, unless essential.', 'Rörelseanimation som triggas av interaktion kan inaktiveras, om den inte är väsentlig.', 'https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions', 'https://www.w3.org/WAI/WCAG22/Techniques/#animation-from-interactions'),

-- Guideline 2.4: Navigable
('2.4.1', 2, '2.4', 'A', 'Bypass Blocks', 'Hoppa över block', 'A mechanism is available to bypass blocks of content that are repeated on multiple pages.', 'En mekanism finns tillgänglig för att hoppa över innehållsblock som upprepas på flera sidor.', 'https://www.w3.org/WAI/WCAG22/Understanding/bypass-blocks', 'https://www.w3.org/WAI/WCAG22/Techniques/#bypass-blocks'),
('2.4.2', 2, '2.4', 'A', 'Page Titled', 'Sidtitel', 'Pages have titles that describe topic or purpose.', 'Sidor har titlar som beskriver ämne eller syfte.', 'https://www.w3.org/WAI/WCAG22/Understanding/page-titled', 'https://www.w3.org/WAI/WCAG22/Techniques/#page-titled'),
('2.4.3', 2, '2.4', 'A', 'Focus Order', 'Fokusordning', 'Components receive focus in an order that preserves meaning and operability.', 'Komponenter får fokus i en ordning som bevarar betydelse och användbarhet.', 'https://www.w3.org/WAI/WCAG22/Understanding/focus-order', 'https://www.w3.org/WAI/WCAG22/Techniques/#focus-order'),
('2.4.4', 2, '2.4', 'A', 'Link Purpose (In Context)', 'Länksyfte (i kontext)', 'The purpose of each link can be determined from the link text alone or together with context.', 'Syftet med varje länk kan bestämmas från länktexten ensam eller tillsammans med kontext.', 'https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context', 'https://www.w3.org/WAI/WCAG22/Techniques/#link-purpose-in-context'),
('2.4.5', 2, '2.4', 'AA', 'Multiple Ways', 'Flera sätt', 'More than one way is available to locate a page within a set of pages.', 'Mer än ett sätt finns tillgängligt för att hitta en sida inom en uppsättning sidor.', 'https://www.w3.org/WAI/WCAG22/Understanding/multiple-ways', 'https://www.w3.org/WAI/WCAG22/Techniques/#multiple-ways'),
('2.4.6', 2, '2.4', 'AA', 'Headings and Labels', 'Rubriker och etiketter', 'Headings and labels describe topic or purpose.', 'Rubriker och etiketter beskriver ämne eller syfte.', 'https://www.w3.org/WAI/WCAG22/Understanding/headings-and-labels', 'https://www.w3.org/WAI/WCAG22/Techniques/#headings-and-labels'),
('2.4.7', 2, '2.4', 'AA', 'Focus Visible', 'Synligt fokus', 'Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible.', 'Alla tangentbordsoperabla användargränssnitt har ett driftläge där tangentbordsfokusindikatorn är synlig.', 'https://www.w3.org/WAI/WCAG22/Understanding/focus-visible', 'https://www.w3.org/WAI/WCAG22/Techniques/#focus-visible'),
('2.4.8', 2, '2.4', 'AAA', 'Location', 'Plats', 'Information about the user''s location within a set of pages is available.', 'Information om användarens plats inom en uppsättning sidor finns tillgänglig.', 'https://www.w3.org/WAI/WCAG22/Understanding/location', 'https://www.w3.org/WAI/WCAG22/Techniques/#location'),
('2.4.9', 2, '2.4', 'AAA', 'Link Purpose (Link Only)', 'Länksyfte (endast länk)', 'A mechanism is available to allow the purpose of each link to be identified from link text alone.', 'En mekanism finns tillgänglig för att tillåta att syftet med varje länk identifieras från länktexten ensam.', 'https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-link-only', 'https://www.w3.org/WAI/WCAG22/Techniques/#link-purpose-link-only'),
('2.4.10', 2, '2.4', 'AAA', 'Section Headings', 'Avsnittsrubriker', 'Section headings are used to organize the content.', 'Avsnittsrubriker används för att organisera innehållet.', 'https://www.w3.org/WAI/WCAG22/Understanding/section-headings', 'https://www.w3.org/WAI/WCAG22/Techniques/#section-headings'),
('2.4.11', 2, '2.4', 'AA', 'Focus Not Obscured (Minimum)', 'Fokus inte dolt (minimum)', 'When a component receives keyboard focus, the component is not entirely hidden by author-created content.', 'När en komponent får tangentbordsfokus är komponenten inte helt dold av författarskapat innehåll.', 'https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum', 'https://www.w3.org/WAI/WCAG22/Techniques/#focus-not-obscured-minimum'),
('2.4.12', 2, '2.4', 'AAA', 'Focus Not Obscured (Enhanced)', 'Fokus inte dolt (förbättrad)', 'When a component receives keyboard focus, no part of the component is hidden by author-created content.', 'När en komponent får tangentbordsfokus är ingen del av komponenten dold av författarskapat innehåll.', 'https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-enhanced', 'https://www.w3.org/WAI/WCAG22/Techniques/#focus-not-obscured-enhanced'),
('2.4.13', 2, '2.4', 'AAA', 'Focus Appearance', 'Fokusutseende', 'The focus indicator has sufficient size and contrast.', 'Fokusindikatorn har tillräcklig storlek och kontrast.', 'https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance', 'https://www.w3.org/WAI/WCAG22/Techniques/#focus-appearance'),

-- Guideline 2.5: Input Modalities
('2.5.1', 2, '2.5', 'A', 'Pointer Gestures', 'Pekargester', 'All functionality that uses multipoint or path-based gestures can be operated with a single pointer.', 'All funktionalitet som använder flerpunkts- eller vägbaserade gester kan användas med en enda pekare.', 'https://www.w3.org/WAI/WCAG22/Understanding/pointer-gestures', 'https://www.w3.org/WAI/WCAG22/Techniques/#pointer-gestures'),
('2.5.2', 2, '2.5', 'A', 'Pointer Cancellation', 'Pekaravbrytning', 'For functionality that can be operated using a single pointer, at least one of several conditions is true.', 'För funktionalitet som kan användas med en enda pekare är minst ett av flera villkor sant.', 'https://www.w3.org/WAI/WCAG22/Understanding/pointer-cancellation', 'https://www.w3.org/WAI/WCAG22/Techniques/#pointer-cancellation'),
('2.5.3', 2, '2.5', 'A', 'Label in Name', 'Etikett i namn', 'For user interface components with labels that include text or images of text, the name contains the visible label text.', 'För användargränssnittskomponenter med etiketter som innehåller text eller bilder av text, innehåller namnet den synliga etiketttexten.', 'https://www.w3.org/WAI/WCAG22/Understanding/label-in-name', 'https://www.w3.org/WAI/WCAG22/Techniques/#label-in-name'),
('2.5.4', 2, '2.5', 'A', 'Motion Actuation', 'Rörelseaktivering', 'Functionality that can be operated by device motion or user motion can also be operated by user interface components.', 'Funktionalitet som kan användas genom enhetsrörelse eller användarrörelse kan också användas av användargränssnittskomponenter.', 'https://www.w3.org/WAI/WCAG22/Understanding/motion-actuation', 'https://www.w3.org/WAI/WCAG22/Techniques/#motion-actuation'),
('2.5.5', 2, '2.5', 'AAA', 'Target Size (Enhanced)', 'Målstorlek (förbättrad)', 'The size of the target for pointer inputs is at least 44 by 44 CSS pixels.', 'Storleken på målet för pekarinmatningar är minst 44 gånger 44 CSS-pixlar.', 'https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced', 'https://www.w3.org/WAI/WCAG22/Techniques/#target-size-enhanced'),
('2.5.6', 2, '2.5', 'A', 'Concurrent Input Mechanisms', 'Samtidiga inmatningsmekanismer', 'Web content does not restrict use of input modalities available on a platform.', 'Webbinnehåll begränsar inte användningen av inmatningsmodaliteter som finns tillgängliga på en plattform.', 'https://www.w3.org/WAI/WCAG22/Understanding/concurrent-input-mechanisms', 'https://www.w3.org/WAI/WCAG22/Techniques/#concurrent-input-mechanisms'),
('2.5.7', 2, '2.5', 'AA', 'Dragging Movements', 'Dragrörelser', 'All functionality that uses a dragging movement can be achieved by a single pointer without dragging.', 'All funktionalitet som använder en dragrörelse kan uppnås med en enda pekare utan att dra.', 'https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements', 'https://www.w3.org/WAI/WCAG22/Techniques/#dragging-movements'),
('2.5.8', 2, '2.5', 'AA', 'Target Size (Minimum)', 'Målstorlek (minimum)', 'The size of the target for pointer inputs is at least 24 by 24 CSS pixels.', 'Storleken på målet för pekarinmatningar är minst 24 gånger 24 CSS-pixlar.', 'https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum', 'https://www.w3.org/WAI/WCAG22/Techniques/#target-size-minimum'),

-- ============================================
-- PRINCIPLE 3: UNDERSTANDABLE
-- ============================================

-- Guideline 3.1: Readable
('3.1.1', 3, '3.1', 'A', 'Language of Page', 'Sidans språk', 'The default human language of each page can be programmatically determined.', 'Standardspråket för varje sida kan bestämmas programmatiskt.', 'https://www.w3.org/WAI/WCAG22/Understanding/language-of-page', 'https://www.w3.org/WAI/WCAG22/Techniques/#language-of-page'),
('3.1.2', 3, '3.1', 'AA', 'Language of Parts', 'Språk för delar', 'The human language of each passage or phrase can be programmatically determined.', 'Det mänskliga språket för varje stycke eller fras kan bestämmas programmatiskt.', 'https://www.w3.org/WAI/WCAG22/Understanding/language-of-parts', 'https://www.w3.org/WAI/WCAG22/Techniques/#language-of-parts'),
('3.1.3', 3, '3.1', 'AAA', 'Unusual Words', 'Ovanliga ord', 'A mechanism is available for identifying specific definitions of words or phrases used in an unusual or restricted way.', 'En mekanism finns tillgänglig för att identifiera specifika definitioner av ord eller fraser som används på ett ovanligt eller begränsat sätt.', 'https://www.w3.org/WAI/WCAG22/Understanding/unusual-words', 'https://www.w3.org/WAI/WCAG22/Techniques/#unusual-words'),
('3.1.4', 3, '3.1', 'AAA', 'Abbreviations', 'Förkortningar', 'A mechanism for identifying the expanded form or meaning of abbreviations is available.', 'En mekanism för att identifiera den utökade formen eller betydelsen av förkortningar finns tillgänglig.', 'https://www.w3.org/WAI/WCAG22/Understanding/abbreviations', 'https://www.w3.org/WAI/WCAG22/Techniques/#abbreviations'),
('3.1.5', 3, '3.1', 'AAA', 'Reading Level', 'Läsnivå', 'When text requires reading ability more advanced than lower secondary education level, supplemental content is available.', 'När text kräver läsförmåga mer avancerad än högstadienivå, finns kompletterande innehåll tillgängligt.', 'https://www.w3.org/WAI/WCAG22/Understanding/reading-level', 'https://www.w3.org/WAI/WCAG22/Techniques/#reading-level'),
('3.1.6', 3, '3.1', 'AAA', 'Pronunciation', 'Uttal', 'A mechanism is available for identifying specific pronunciation of words where meaning is ambiguous without knowing the pronunciation.', 'En mekanism finns tillgänglig för att identifiera specifikt uttal av ord där betydelsen är tvetydig utan att känna till uttalet.', 'https://www.w3.org/WAI/WCAG22/Understanding/pronunciation', 'https://www.w3.org/WAI/WCAG22/Techniques/#pronunciation'),

-- Guideline 3.2: Predictable
('3.2.1', 3, '3.2', 'A', 'On Focus', 'Vid fokus', 'When any component receives focus, it does not initiate a change of context.', 'När en komponent får fokus initierar den inte en kontextändring.', 'https://www.w3.org/WAI/WCAG22/Understanding/on-focus', 'https://www.w3.org/WAI/WCAG22/Techniques/#on-focus'),
('3.2.2', 3, '3.2', 'A', 'On Input', 'Vid inmatning', 'Changing the setting of any user interface component does not automatically cause a change of context.', 'Att ändra inställningen för en användargränssnittskomponent orsakar inte automatiskt en kontextändring.', 'https://www.w3.org/WAI/WCAG22/Understanding/on-input', 'https://www.w3.org/WAI/WCAG22/Techniques/#on-input'),
('3.2.3', 3, '3.2', 'AA', 'Consistent Navigation', 'Konsekvent navigering', 'Navigational mechanisms that are repeated on multiple pages occur in the same relative order each time they are repeated.', 'Navigeringsmekanismer som upprepas på flera sidor förekommer i samma relativa ordning varje gång de upprepas.', 'https://www.w3.org/WAI/WCAG22/Understanding/consistent-navigation', 'https://www.w3.org/WAI/WCAG22/Techniques/#consistent-navigation'),
('3.2.4', 3, '3.2', 'AA', 'Consistent Identification', 'Konsekvent identifiering', 'Components that have the same functionality within a set of pages are identified consistently.', 'Komponenter som har samma funktionalitet inom en uppsättning sidor identifieras konsekvent.', 'https://www.w3.org/WAI/WCAG22/Understanding/consistent-identification', 'https://www.w3.org/WAI/WCAG22/Techniques/#consistent-identification'),
('3.2.5', 3, '3.2', 'AAA', 'Change on Request', 'Ändring på begäran', 'Changes of context are initiated only by user request or a mechanism is available to turn off such changes.', 'Kontextändringar initieras endast på användarens begäran eller en mekanism finns tillgänglig för att stänga av sådana ändringar.', 'https://www.w3.org/WAI/WCAG22/Understanding/change-on-request', 'https://www.w3.org/WAI/WCAG22/Techniques/#change-on-request'),
('3.2.6', 3, '3.2', 'A', 'Consistent Help', 'Konsekvent hjälp', 'If a page contains help mechanisms, they occur in the same relative order on each page.', 'Om en sida innehåller hjälpmekanismer förekommer de i samma relativa ordning på varje sida.', 'https://www.w3.org/WAI/WCAG22/Understanding/consistent-help', 'https://www.w3.org/WAI/WCAG22/Techniques/#consistent-help'),

-- Guideline 3.3: Input Assistance
('3.3.1', 3, '3.3', 'A', 'Error Identification', 'Felidentifiering', 'If an input error is automatically detected, the item that is in error is identified and described to the user in text.', 'Om ett inmatningsfel upptäcks automatiskt, identifieras och beskrivs det felaktiga objektet för användaren i text.', 'https://www.w3.org/WAI/WCAG22/Understanding/error-identification', 'https://www.w3.org/WAI/WCAG22/Techniques/#error-identification'),
('3.3.2', 3, '3.3', 'A', 'Labels or Instructions', 'Etiketter eller instruktioner', 'Labels or instructions are provided when content requires user input.', 'Etiketter eller instruktioner tillhandahålls när innehåll kräver användarinmatning.', 'https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions', 'https://www.w3.org/WAI/WCAG22/Techniques/#labels-or-instructions'),
('3.3.3', 3, '3.3', 'AA', 'Error Suggestion', 'Felförslag', 'If an input error is automatically detected and suggestions for correction are known, then the suggestions are provided to the user.', 'Om ett inmatningsfel upptäcks automatiskt och förslag på korrigering är kända, tillhandahålls förslagen till användaren.', 'https://www.w3.org/WAI/WCAG22/Understanding/error-suggestion', 'https://www.w3.org/WAI/WCAG22/Techniques/#error-suggestion'),
('3.3.4', 3, '3.3', 'AA', 'Error Prevention (Legal, Financial, Data)', 'Felförebyggande (juridiskt, ekonomiskt, data)', 'For pages that cause legal commitments or financial transactions, submissions are reversible, checked, or confirmed.', 'För sidor som orsakar juridiska åtaganden eller finansiella transaktioner är inlämningar reversibla, kontrollerade eller bekräftade.', 'https://www.w3.org/WAI/WCAG22/Understanding/error-prevention-legal-financial-data', 'https://www.w3.org/WAI/WCAG22/Techniques/#error-prevention-legal-financial-data'),
('3.3.5', 3, '3.3', 'AAA', 'Help', 'Hjälp', 'Context-sensitive help is available.', 'Kontextkänslig hjälp finns tillgänglig.', 'https://www.w3.org/WAI/WCAG22/Understanding/help', 'https://www.w3.org/WAI/WCAG22/Techniques/#help'),
('3.3.6', 3, '3.3', 'AAA', 'Error Prevention (All)', 'Felförebyggande (alla)', 'For pages that require user submissions, submissions are reversible, checked, or confirmed.', 'För sidor som kräver användarinlämningar är inlämningar reversibla, kontrollerade eller bekräftade.', 'https://www.w3.org/WAI/WCAG22/Understanding/error-prevention-all', 'https://www.w3.org/WAI/WCAG22/Techniques/#error-prevention-all'),
('3.3.7', 3, '3.3', 'A', 'Redundant Entry', 'Överflödig inmatning', 'Information previously entered by or provided to the user that is required to be entered again is auto-populated or available for selection.', 'Information som tidigare matats in av eller tillhandahållits till användaren och som krävs att matas in igen fylls i automatiskt eller är tillgänglig för val.', 'https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry', 'https://www.w3.org/WAI/WCAG22/Techniques/#redundant-entry'),
('3.3.8', 3, '3.3', 'AA', 'Accessible Authentication (Minimum)', 'Tillgänglig autentisering (minimum)', 'A cognitive function test is not required for any step in an authentication process unless an alternative is provided.', 'Ett kognitivt funktionstest krävs inte för något steg i en autentiseringsprocess om inte ett alternativ tillhandahålls.', 'https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum', 'https://www.w3.org/WAI/WCAG22/Techniques/#accessible-authentication-minimum'),
('3.3.9', 3, '3.3', 'AAA', 'Accessible Authentication (Enhanced)', 'Tillgänglig autentisering (förbättrad)', 'A cognitive function test is not required for any step in an authentication process.', 'Ett kognitivt funktionstest krävs inte för något steg i en autentiseringsprocess.', 'https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-enhanced', 'https://www.w3.org/WAI/WCAG22/Techniques/#accessible-authentication-enhanced'),

-- ============================================
-- PRINCIPLE 4: ROBUST
-- ============================================

-- Guideline 4.1: Compatible
('4.1.1', 4, '4.1', 'A', 'Parsing', 'Tolkning', 'In content implemented using markup languages, elements have complete start and end tags, are nested according to their specifications, do not contain duplicate attributes, and any IDs are unique. Note: This criterion is obsolete in WCAG 2.2.', 'I innehåll som implementerats med märkspråk har element kompletta start- och sluttaggar, är nästlade enligt sina specifikationer, innehåller inte dubblerade attribut, och alla ID:n är unika. Obs: Detta kriterium är föråldrat i WCAG 2.2.', 'https://www.w3.org/WAI/WCAG22/Understanding/parsing', 'https://www.w3.org/WAI/WCAG22/Techniques/#parsing'),
('4.1.2', 4, '4.1', 'A', 'Name, Role, Value', 'Namn, roll, värde', 'For all user interface components, the name and role can be programmatically determined; states, properties, and values can be programmatically set.', 'För alla användargränssnittskomponenter kan namn och roll bestämmas programmatiskt; tillstånd, egenskaper och värden kan ställas in programmatiskt.', 'https://www.w3.org/WAI/WCAG22/Understanding/name-role-value', 'https://www.w3.org/WAI/WCAG22/Techniques/#name-role-value'),
('4.1.3', 4, '4.1', 'AA', 'Status Messages', 'Statusmeddelanden', 'Status messages can be programmatically determined through role or properties such that they can be presented to the user by assistive technologies without receiving focus.', 'Statusmeddelanden kan bestämmas programmatiskt genom roll eller egenskaper så att de kan presenteras för användaren av hjälpmedel utan att få fokus.', 'https://www.w3.org/WAI/WCAG22/Understanding/status-messages', 'https://www.w3.org/WAI/WCAG22/Techniques/#status-messages')

ON CONFLICT (id) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_sv = EXCLUDED.name_sv,
  description_en = EXCLUDED.description_en,
  description_sv = EXCLUDED.description_sv,
  understanding_url = EXCLUDED.understanding_url,
  techniques_url = EXCLUDED.techniques_url;
